Fix type import, so it works in the publised package (#168)
Getting this error otherwise:
```
node_modules/defender-sentinel-client/lib/models/blockwatcher.d.ts:2:38 - error TS2307: Cannot find module 'defender-sentinel-client/src/models/subscriber' or its corresponding type declarations.

2 import { SentinelConfirmation } from 'defender-sentinel-client/src/models/subscriber';
```